// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class NGORegistrationTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void nGORegistration() {
    driver.get("https://ektafund.onrender.com/");
    driver.manage().window().setSize(new Dimension(1294, 814));
    driver.findElement(By.cssSelector(".land-getstarted > img")).click();
    driver.findElement(By.cssSelector(".land-option-button:nth-child(1) > .land-option-image")).click();
    driver.findElement(By.id("form2Example17")).click();
    driver.findElement(By.id("form2Example17")).sendKeys("rj@gmail.com");
    driver.findElement(By.id("form2Example27")).click();
    driver.findElement(By.id("form2Example27")).sendKeys("https://ektafund.onrender.com/admin-dashboard");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.id("form2Example27")).click();
    driver.findElement(By.id("form2Example27")).click();
    {
      WebElement element = driver.findElement(By.id("form2Example27"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("form2Example27")).click();
    driver.findElement(By.id("form2Example27")).sendKeys("123456789Qw@");
    driver.findElement(By.id("form2Example27")).sendKeys(Keys.ENTER);
    driver.findElement(By.linkText("Register Your Organization")).click();
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys("Rishabh2");
    driver.findElement(By.name("location")).click();
    driver.findElement(By.name("location")).sendKeys("Delhi");
    driver.findElement(By.name("causeArea")).click();
    driver.findElement(By.name("causeArea")).sendKeys("Health");
    driver.findElement(By.name("vision")).click();
    driver.findElement(By.name("vision")).sendKeys("to improve health of all");
    driver.findElement(By.name("mission")).click();
    driver.findElement(By.name("mission")).sendKeys("health facilitation ");
    driver.findElement(By.name("contactPerson")).click();
    driver.findElement(By.name("contactPerson")).sendKeys("Rishabh Jain");
    driver.findElement(By.name("mobileNumber")).click();
    driver.findElement(By.name("mobileNumber")).sendKeys("2345678982");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("rj2@gmail.com");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("Qwerty1@");
    driver.findElement(By.name("address")).click();
    driver.findElement(By.name("address")).sendKeys("delhi");
    driver.findElement(By.cssSelector("button:nth-child(13)")).click();
    driver.findElement(By.name("updated12A")).click();
    driver.findElement(By.name("updated12A")).sendKeys("C:\\fakepath\\Screenshot_2024-11-01_180831-removebg-preview.png");
    driver.findElement(By.name("updated80G")).click();
    driver.findElement(By.name("updated80G")).sendKeys("C:\\fakepath\\Screenshot_2024-11-01_180831-removebg-preview.png");
    driver.findElement(By.cssSelector("button:nth-child(13)")).click();
    assertThat(driver.switchTo().alert().getText(), is("NGO registered successfully!"));
    driver.close();
  }
}
